on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Install Dependencies
        run: sudo apt-get install -y ffmpeg webp
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: Run Tests
        run: ./test/bats/bin/bats test/*.bats
