on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Install Dependencies
        run: sudo apt-get install -y ffmpeg webp
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@2.0.0
      - name: Run Tests
        run: bats --verbose-run ./test
        env:
          BATS_LIB_PATH: "/usr/lib"
